{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinepods.fullname" . }}-backend
  labels:
    {{- include "pinepods.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.backend.secrets.apiKey | quote }}
  API_SECRET: {{ .Values.backend.secrets.apiSecret | quote }}
  YOUTUBE_API_KEY: {{ .Values.backend.secrets.youtubeApiKey | quote }}
{{- end }}