// Copyright 2020 Ben Hills and the project contributors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
import 'package:flutter/widgets.dart';
import 'package:pinepods_mobile/l10n/app_localizations.dart';

/// Backwards-compatible shim around the gen-l10n generated [AppLocalizations].
///
/// The app historically accessed localized strings via `L.of(context)!.some_key`.
/// Localization is now generated by Flutter's built-in `gen-l10n` from the ARB
/// files in this directory (run automatically on build via `generate: true`).
/// This shim keeps every existing call site working unchanged: because the ARB
/// keys map 1:1 to the generated getters, `L.of(context)!.some_key` resolves to
/// `AppLocalizations.of(context)!.some_key`.
class L {
  static AppLocalizations? of(BuildContext context) => AppLocalizations.of(context);
}
